local TimeClient = require(script.Time.TimeClient)
local FarmClient = require(script.Farm.FarmClient)
local HubClient = require(script.Hub.HubClient)
local StardewHud = require(script.UI.StardewHud)
local HubUi = require(script.UI.HubUi)

TimeClient.init()
FarmClient.init()
HubClient.init()
StardewHud.init()
HubUi.init()
